# Generated by Django 6.0.6 on 2026-06-24 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Instruções ou detalhes da tarefa.')),
                ('categoria', models.CharField(choices=[('LISTA', 'Lista Mensal / Cronograma'), ('REDACAO', 'Redação'), ('SIMULADO', 'Simulado (TRIEduc)'), ('PLANEJAMENTO', 'Planejamento e Estratégia'), ('GENERICA', 'Tarefa Personalizada')], default='GENERICA', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=15)),
                ('data_limite', models.DateField(blank=True, help_text='Opcional. Prazo final para conclusão.', null=True)),
                ('link_externo', models.URLField(blank=True, help_text='Opcional. Link para o site do Salvaguarda ou material extra.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'tipo': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.ForeignKey(limit_choices_to={'tipo': 'TUTORADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['status', 'data_limite', '-data_criacao'],
            },
        ),
    ]
