# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Opcional. Breve resumo do conteúdo.')),
                ('tipo', models.CharField(choices=[('ARQUIVO', 'Arquivo (PDF, Imagem, Documento)'), ('LINK', 'Link Externo')], default='LINK', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/%Y/%m/')),
                ('url', models.URLField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_enviados', to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.ForeignKey(help_text='Estudante ao qual este material pertence', limit_choices_to={'tipo': 'TUTORADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-data_envio'],
            },
        ),
    ]
