# Generated by Django 6.0.6 on 2026-06-13 15:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('TUTOR', 'Tutor'), ('TUTORADO', 'Tutorado')], max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('disponibilidade', models.TextField(blank=True, null=True)),
                ('max_tutorados', models.PositiveIntegerField(default=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Tutor',
                'verbose_name_plural': 'Perfis dos Tutores',
            },
        ),
        migrations.CreateModel(
            name='PerfilTutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('1EM', '1º Ano do Ensino Médio'), ('2EM', '2º Ano do Ensino Médio'), ('3EM', '3º Ano do Ensino Médio'), ('FORM', 'Já formado / Cursinho')], default='3EM', max_length=4)),
                ('fez_enem', models.BooleanField(default=False)),
                ('cursos_interesse', models.TextField(blank=True)),
                ('escola', models.CharField(blank=True, max_length=200, null=True)),
                ('turno_escolar', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('responsavel_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('objetivo_principal', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=16, unique=True)),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutorado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Tutorado',
                'verbose_name_plural': 'Perfis dos Tutorados',
            },
        ),
    ]
