# Generated by Django 6.0.6 on 2026-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiltutorado',
            name='responsavel_nome',
        ),
        migrations.RemoveField(
            model_name='perfiltutorado',
            name='responsavel_telefone',
        ),
        migrations.AddField(
            model_name='perfiltutorado',
            name='carta_apresentacao',
            field=models.URLField(blank=True, help_text='Link do Drive', null=True),
        ),
        migrations.AddField(
            model_name='perfiltutorado',
            name='trabalha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfiltutorado',
            name='universidade_pretendida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
