# Generated by Django 5.2.1 on 2026-06-09 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o usuário está ativo no sistema'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade onde reside', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cursos_interesse',
            field=models.TextField(blank=True, help_text='Cursos de interesse (apenas para tutorados)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do usuário', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_ultimo_acesso',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último acesso', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo do usuário', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado (sigla) onde reside', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ja_fez_enem',
            field=models.BooleanField(default=False, help_text='Indica se já fez o ENEM (apenas para tutorados)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o usuário', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='serie_escolar',
            field=models.CharField(blank=True, help_text='Série escolar atual (apenas para tutorados)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TUTOR', 'Tutor'), ('TUTORADO', 'Tutorado')], help_text='Tipo de usuário no sistema', max_length=10),
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, help_text='Área de especialidade do tutor', max_length=100, null=True)),
                ('experiencia', models.TextField(blank=True, help_text='Experiência profissional ou acadêmica', null=True)),
                ('disponibilidade', models.TextField(blank=True, help_text='Horários disponíveis para tutoria', null=True)),
                ('max_tutorados', models.PositiveIntegerField(default=10, help_text='Número máximo de tutorados que pode acompanhar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Tutor',
                'verbose_name_plural': 'Perfis dos Tutores',
            },
        ),
        migrations.CreateModel(
            name='PerfilTutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(blank=True, help_text='Nome da escola onde estuda', max_length=200, null=True)),
                ('turno_escolar', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], help_text='Turno que estuda', max_length=20, null=True)),
                ('responsavel_nome', models.CharField(blank=True, help_text='Nome do responsável', max_length=200, null=True)),
                ('responsavel_telefone', models.CharField(blank=True, help_text='Telefone do responsável', max_length=15, null=True)),
                ('objetivo_principal', models.TextField(blank=True, help_text='Principal objetivo com a tutoria', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutorado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Tutorado',
                'verbose_name_plural': 'Perfis dos Tutorados',
            },
        ),
    ]
