# Generated by Django 6.0.6 on 2026-06-13 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('link', models.URLField(blank=True, help_text='Link do Google Meet, Zoom, etc.')),
                ('topicos', models.TextField(blank=True)),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('observacoes', models.TextField(blank=True)),
                ('presenca', models.BooleanField(default=False)),
                ('materia', models.CharField(choices=[('MAT', 'Matemática'), ('POR', 'Português / Redação'), ('CIE', 'Ciências da Natureza'), ('HUM', 'Ciências Humanas'), ('LIN', 'Linguagens'), ('GER', 'Geral / Orientação')], default='GER', max_length=3)),
                ('tutor', models.ForeignKey(limit_choices_to={'tipo': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_como_tutor', to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.ForeignKey(limit_choices_to={'tipo': 'TUTORADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_como_tutorado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
