# Generated by Django 5.2.1 on 2025-05-27 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_tutorados/')),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('fez_enem', models.BooleanField(default=False)),
                ('cursos_interesse', models.TextField()),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('link', models.URLField(help_text='Link do Google Meet, Zoom, etc.')),
                ('topicos', models.TextField()),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('presenca', models.BooleanField(default=False)),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='tutorias.tutorado')),
            ],
        ),
    ]
