# Generated by Django 6.0.6 on 2026-06-22 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='agendado_por',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('TUTORADO', 'Tutorado')], default='TUTOR', help_text='Quem criou o agendamento', max_length=10),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='CONFIRMADA', max_length=12),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='DisponibilidadeRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'tipo': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('tutor', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
