# Generated by Django 6.0.6 on 2026-06-24 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0002_reuniao_agendado_por_reuniao_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('info_salvaguarda', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Funcionamento do Salvaguarda')),
                ('info_publica_privada', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Diferença entre universidade pública e privada')),
                ('info_vestibulares', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='O que é vestibular e opções disponíveis')),
                ('info_enem_programas', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='ENEM, SISU, PROUNI e FIES')),
                ('info_nota_corte', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Conceito de nota de corte')),
                ('info_universidades_regiao', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Universidades da região e cursos')),
                ('info_assistencia', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Programas de assistência estudantil')),
                ('info_bolsas_privadas', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Mecanismo de bolsas em privadas')),
                ('org_rotina', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Segue rotina e cronograma')),
                ('org_estuda_sozinho', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Estuda sozinho e concilia tarefas')),
                ('org_estudo_ativo', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Estudo ativo (Exercícios e Simulados)')),
                ('org_estudo_eficiente', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('RAZOAVEL', 'Razoável'), ('BAIXO', 'Baixo'), ('NULO', 'Nulo')], default='NULO', max_length=15, verbose_name='Estuda de forma eficiente')),
                ('maiores_dificuldades', models.TextField(blank=True, help_text='Principais barreiras notadas na reunião.', null=True)),
                ('pontos_positivos', models.TextField(blank=True, help_text='Qualidades e facilidades do estudante.', null=True)),
                ('comentarios_extras', models.TextField(blank=True, help_text='Demandas extras ou observações livres.', null=True, verbose_name='Demais comentários')),
                ('tutor', models.ForeignKey(limit_choices_to={'tipo': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_preenchidas', to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.OneToOneField(limit_choices_to={'tipo': 'TUTORADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ficha_diagnostica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Diagnóstica',
                'verbose_name_plural': 'Fichas Diagnósticas',
            },
        ),
    ]
