# Generated by Django 6.0.6 on 2026-06-24 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0003_fichadiagnostica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Atividade')),
                ('descricao', models.CharField(help_text='Ex: Pesquisa de cursos na UFRJ, Leitura do Manual, etc.', max_length=255, verbose_name='Breve Descrição')),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Ex: 90 para 1h30.', verbose_name='Carga Horária (em minutos)')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'tipo': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extras', to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TUTORADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade Extra',
                'verbose_name_plural': 'Atividades Extras',
                'ordering': ['-data', '-data_registro'],
            },
        ),
    ]
