# Generated by Django 6.0.6 on 2026-06-24 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0004_atividadeextra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fim_semana', models.DateField(verbose_name='Referente à semana de:')),
                ('status', models.CharField(choices=[('TOTAL', 'Consegui cumprir toda a meta'), ('PARCIAL', 'Cumpri parcialmente'), ('NAO', 'Não consegui cumprir o cronograma')], max_length=10)),
                ('observacoes', models.TextField(blank=True, help_text='O que funcionou bem? Teve imprevistos?', verbose_name='Como foi a sua semana?')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkpoint Semanal',
                'verbose_name_plural': 'Checkpoints Semanais',
                'ordering': ['-data_fim_semana'],
            },
        ),
        migrations.CreateModel(
            name='GradeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('disciplina', models.CharField(choices=[('PORTUGUES', 'Português'), ('REDACAO', 'Redação'), ('MATEMATICA', 'Matemática'), ('FISICA', 'Física'), ('QUIMICA', 'Química'), ('BIOLOGIA', 'Biologia'), ('HISTORIA', 'História'), ('GEOGRAFIA', 'Geografia'), ('FILOSOFIA', 'Filosofia'), ('SOCIOLOGIA', 'Sociologia'), ('LINGUAS', 'Língua Estrangeira'), ('REVISAO', 'Revisão / Simulados')], max_length=20)),
                ('quinzenal', models.BooleanField(default=False, help_text='Marque se esta disciplina for alternada com outra no mesmo horário.', verbose_name='Alternar a cada 15 dias?')),
                ('tutorado', models.ForeignKey(limit_choices_to={'tipo': 'TUTORADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='grade_estudos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloco de Estudo',
                'verbose_name_plural': 'Grade de Estudos',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
    ]
